name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t $DOCKER_USERNAME/joblytics-frontend .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push $DOCKER_USERNAME/joblytics-frontend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: sudo docker pull $DOCKER_USERNAME/joblytics-frontend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - run: sudo bash ./killdocker.sh
      - run: sudo docker run -p 80:8000 -d $DOCKER_USERNAME/joblytics-frontend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
